### ISSUE TITLE
Export class instead of instance

### ISSUE THREAD

**Issue by insolite** [marvinroger/node-rcswitch#13]
How about exporting of class instead of already created instance [here](https://github.com/marvinroger/node-rcswitch/blob/d216e43d25756ee4baaf57200260baae4138b018/index.js#L3)?
Some kind of
```js
module.exports = rcswitch.RCSwitch;
```
I understand that this appear to be a compatibility breaking update, so we can think of another exporting way or making of major version bump.

Let me clarify why it's important.
Sometimes it's good to have different instances of `RcSwitch` for different purposes. It may be very useful especially alongside the [code receiving](https://github.com/marvinroger/node-rcswitch/issues/11). In `rcswitch` there is a [disabling of receiving](https://github.com/sui77/rc-switch/blob/a9da9c36820b02fc5613dfe2437e1187bcf5b402/RCSwitch.cpp#L492-L496) while transmitting data, so theoretically it should work simultaneously. But in fact there are some issues with receiving after transmission. I didn't dig much in that problem cause:
1. It works perfectly with 2 instances of `RcSwitch` anyway.
2. We don't need to stop receiving at all cause we're using different PINs for sending and receiving.

**Comment by slash-oleh** [comment]
Well, I think I found the reason for breaking of signal receiving after transmitting. First off, that happends when the `rcswitch` is disabling/enabling receiving while transmitting. I've described details [here](https://github.com/sui77/rc-switch/issues/192) for `rc-switch` repo.
