### ISSUE TITLE
Doesn't work with Node 0.12.x

### ISSUE THREAD

**Issue by ghost** [marvinroger/node-rcswitch#2]
Is that it will work with nodejs 0.12.x ?

**Comment by marvinroger** [comment]
It should not be too hard to do, just look at the [C++ API breaking changes](https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/) from 0.10.x to 0.12.x. However, I won't update the module for now as a lot of RPi modules, like [node-red](https://github.com/node-red/node-red) doesn't yet support Node 0.12.x.

Feel free to make a PR though, I could merge it once other modules are compatible.

**Comment by marvinroger** [comment]
I am working on it right now. It should be out soon!

**Comment by marvinroger** [comment]
As of 0.2.2, it is working with Node 0.12, and still compatible with 0.10 thanks to Nan.
